export const mockData1 = [
  {
    id: 1,
    Name: "Caleb Adewunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 2,
    Name: "Karim Adeyemi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 3,
    Name: "Ayileka Omowunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 4,
    Name: "Caleb Adewunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 5,
    Name: "Karim Adeyemi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 6,
    Name: "Caleb Adewunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 7,
    Name: "Caleb Adewunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 8,
    Name: "Caleb Adewunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },
  {
    id: 9,
    Name: "Ayileka Omowunmi",
    Email: "contacts@gmail.com",
    Contact: "8899342774",
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    DateRegistered: "July 21st,2024",
  },

  // Add more mock transactions here...
];
