export const mockData1 = [
  {
    id: 1,
    StaffID: "6596d5fa50...",
    Name: "Karim Adeyemi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Acounting",
  },
  {
    id: 2,
    StaffID: "6596d5fa50...",
    Name: "Joseph olabisi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Marketing",
  },
  {
    id: 3,
    StaffID: "6596d5fa50...",
    Name: "Ayileka Wunmi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Recovery ",
  },
  {
    id: 4,
    StaffID: "6596d5fa50...",
    Name: "Karim Adeyemi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Recovery ",
  },
  {
    id: 5,
    StaffID: "6596d5fa50...",
    Name: "Olaleye Seun",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Recovery ",
  },
  {
    id: 6,
    StaffID: "6596d5fa50...",
    Name: "Karim Adeyemi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Recovery ",
  },
  {
    id: 7,
    StaffID: "6596d5fa50...",
    Name: "Karim Adeyemi",
    Contact: 8899342774,
    Address: "9,aliclose Street Lagos",
    Region: "Ketu",
    Roles: "Admin",
    Department: "Recovery ",
  },

  // Add more mock transactions here...
];
